language: java
sudo: false
script: mvn clean install
notifications: 
    email:
      recipients:
      - rakesh.kanchalwar@bitwiseglobal.com   
    on_success: always
    on_failure: always
env:
  global:
    - "FTP_USER=CapOne"
    - "FTP_PASSWORD=!c@pone#"
addons:
    apt:
        packages:
            - sshpass
after_success:
    "curl --ftp-create-dirs -T /home/travis/build/rakeshkanchalwar/TestSpringBuild/target/Spring3Example-1.0-SNAPSHOT.jar  -u $FTP_USER:$FTP_PASSWORD ftp://ftp.bitwiseglobal.com:4469"
    
