language: java
sudo: false
script: mvn clean install
notifications: 
    email:
      recipients:
      - rakesh.kanchalwar@bitwiseglobal.com   
    on_success: always
    on_failure: always
env:
  global:
    - "FTP_USER=CapOne"
    - "FTP_PASSWORD=\\!c\\@pone\\#"
addons:
    apt:
        packages:
            - sshpass
after_success:
    - export SSHPASS=\\!c\\@pone\\#
    - sshpass -e scp '/home/travis/build/rakeshkanchalwar/TestSpringBuild/target/Spring3Example-1.0-SNAPSHOT.jar' CapOne@115.111.36.80:test
